config/routes.rb
Rails.application.routes.draw do
  
  scope ':locale', :locale => /#{I18n.available_locales.join("|")}/ do
    get 'login'                          => 'sessions#new'
    post 'login'                         => 'sessions#create'
    delete 'logout'                      => 'sessions#destroy'
    get 'home'                           => 'home_pages#index', as: :home
    get 'about'                          => 'static_pages#about', as: :about
    get 'galery'                         => 'static_pages#galery', as: :galery
    get 'contact'                        => 'static_pages#contact', as: :contact
    get 'user/:id'                       => 'users#show', as: :account
    
    namespace :building do
      resources :laboratory do
        get 'reassign'                    => 'workstation#reassign'
        post 'move'                       => 'workstation#move'
        resources :workstation
      end
      post 'lab/new'                      => 'laboratories#new', as: :new_lab
      post 'lab/create'                   => 'laboratories#create'
      post 'labs'                         => 'laboratories#index'
    end
    resources :building, only: [:create, :new]
  
    get 'dashboard'                       => 'dashboard#index', as: :dashboard
    get 'dashboard/install'               => 'building#new', as: :building_install
    resources :dashboard, only: [:index]

   # TO DO: Change GET to POST
    get 'users/user_mails.json'          => 'users#user_mails'

    scope :dashboard do
      post 'users'                       => 'users#index_for_dashboard'
      scope :users do
        post 'invite_user_form'          => 'users#invite_new'
        post 'invite_user'               => 'users#invite_create'
        post 'permissions'               => 'users#edit_for_dashboard'
        post 'update_for_dashboard'      => 'users#update_for_dashboard'
        post 'remove_user'               => 'users#remove_for_dashboard'
      end
      post 'groups'                      => 'groups#index_for_dashboard', as: :groups
      scope :groups do
        post 'manage'                    => 'groups#manage'
        post 'add_group'                 => 'groups#new'
        post 'remove_group'              => 'groups#remove_group'
        post 'create'                    => 'groups#create'
      end

      post 'logs'                        => 'log#show', as: :logs
      post 'faq'                         => 'static_pages#faq', as: :faq
      post 'issues'                      => 'dashboard#issues', as: :issues
      
      post 'widgets'                     => 'dashboard#widgets_panel', as: :widgets
    end
    root to: redirect(status: 302) {|_,params, _| "/#{params[:locale]}/home"}
  end
  
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :dashboard_assignment, as: :assignable
  has_one :dashboard, through: :dashboard_assignment
  has_many :laboratories_assignments, as: :lab_assignable
  has_many :users_groups
  has_many :users, through: :users_groups

  validates :name, presence: true, uniqueness: false
  validates :dashboard_assignment, presence: true, uniqueness: false
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user
  before_action :set_group, only: [:edit, :update, :destroy]
  before_action :set_groups, only: [:manage, :index_for_dashboard, :remove_group]

  def new
    @group = Group.new
    render layout: false
  end

  def create
    @group = Group.new(group_params)
    @group.dashboard_assignment = DashboardAssignment.new(dashboard: current_dashboard, assignable: @group)
    respond_to do |format|
      if @group.save
        format.js
      else
        format.js
      end
    end
  end

  def edit
    render layout: false
  end

  def update
    respond_to do |format|
      if group.update(group_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :index_for_dashboard, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index_for_dashboard
    render layout: false
  end

  def manage

    render layout: false
  end

  def remove_group

    render layout: false
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def set_groups
      @groups = current_dashboard.groups
    end

    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group, url: 'dashboard/groups/create', remote: true) do |f| %>
    <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:
          </h2>
          <ul>
            <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="fields">
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/groups/index_for_dashboard.html.erb
<div id="show-dashboard-groups" class="dashboard-groups">
  <h1 class="main-header"><%= t('.main_header') %></h1>
  <h2 class="second-header"><%= t('.second_header')%></h2>

  <div class="table-responsive-vertical shadow-z-1 table-striped">
    <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Users</th>
      </tr>
      </thead>
      <tbody>
      <% for group in @groups %>
          <tr>
            <td data-title="ID"><%= group.id %></td>
            <td data-title="Name"><%= group.name %></td>
            <td data-title="Users"><%= group.users.count %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/manage.html.erb
<div>

</div>

app/views/groups/new.html.erb
<h1>Creating Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/remove_group.html.erb
<div>

</div>