config/routes.rb
Rails.application.routes.draw do
  
  scope ':locale', :locale => /#{I18n.available_locales.join("|")}/ do
    get 'login'                          => 'sessions#new'
    post 'login'                         => 'sessions#create'
    delete 'logout'                      => 'sessions#destroy'
    get 'home'                           => 'home_pages#index', as: :home
    get 'about'                          => 'static_pages#about', as: :about
    get 'galery'                         => 'static_pages#galery', as: :galery
    get 'contact'                        => 'static_pages#contact', as: :contact
    get 'user/:id'                       => 'users#show', as: :account
    
    namespace :building do
      resources :laboratory do
        get 'reassign'                    => 'workstation#reassign'
        post 'move'                       => 'workstation#move'
        resources :workstation
      end
      post 'lab/new'                      => 'laboratories#new', as: :new_lab
      post 'lab/create'                   => 'laboratories#create'
      post 'labs'                         => 'laboratories#index'
    end
    resources :building, only: [:create, :new]
  
    get 'dashboard'                       => 'dashboard#index', as: :dashboard
    get 'dashboard/install'               => 'building#new', as: :building_install
    resources :dashboard, only: [:index]

   # TO DO: Change GET to POST
    get 'users/user_mails.json'          => 'users#user_mails'

    scope :dashboard do
      post 'users'                       => 'users#index_for_dashboard'
      scope :users do
        post 'invite_user_form'          => 'users#invite_new'
        post 'invite_user'               => 'users#invite_create'
        post 'permissions'               => 'users#edit_for_dashboard'
        post 'update_for_dashboard'      => 'users#update_for_dashboard'
        post 'remove_user'               => 'users#remove_for_dashboard'
      end
      post 'groups'                      => 'groups#index_for_dashboard', as: :groups
      scope :groups do
        post 'manage'                    => 'groups#manage'
        post 'add_group'                 => 'groups#new'
        post 'remove_group'              => 'groups#remove_group'
        post 'create'                    => 'groups#create'
      end

      post 'logs'                        => 'log#show', as: :logs
      post 'faq'                         => 'static_pages#faq', as: :faq
      post 'issues'                      => 'dashboard#issues', as: :issues
      
      post 'widgets'                     => 'dashboard#widgets_panel', as: :widgets
    end
    root to: redirect(status: 302) {|_,params, _| "/#{params[:locale]}/home"}
  end
  
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  belongs_to :site_role
  has_many :buildings
  has_many :dashboard_assignments, as: :assignable, class_name: 'DashboardAssignment'
  has_many :laboratories_assignments, as: :lab_assignable
  has_many :dashboards, through: :dashboard_assignments
  
  def is_new_user
    is_normal_user || self.site_role == SiteRole.find_by_name('new_user')
  end
  
  def is_normal_user # can create own dashboard
    is_mod || self.site_role == SiteRole.find_by_name('user')
  end
  
  def is_mod
    is_hmod || self.site_role == SiteRole.find_by_name('moderator')
  end
  
  def is_hmod
    is_admin || self.site_role == SiteRole.find_by_name('head_moderator')
  end
  
  def is_admin
    is_hadmin || self.site_role == SiteRole.find_by_name('administrator')
  end
  
  def is_hadmin
    self.site_role == SiteRole.find_by_name('head_administrator')
  end
  
  def current_avatar
    return "default.png"
  end
  
  def public_data_for_dashboard(dashboard)
    da=dashboard.dashboard_assignments
    visible_name + ' <' + email + '> - ' + I18n.t("dashboard_roles." + dashboard.dashboard_assignments.where(assignable: self).take.dashboard_role.name)
  end
  
  def assigments_for_dashboard(dashboard)
    as = current_dashboard_assignments
    as.where(user: self).take
  end
  
  validates :visible_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :site_role, presence: true
  validates :age, presence: true
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  include DashboardHelper
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  # POST /invite_user
  def invite_new
    headers['Last-Modified'] = Time.now.httpdate
   render layout: false
  end

  # POST dashboard/users/invite_user
  def invite_create
    ps = inv_params
    begin
      @user = User.find ps[:selected_mail_id].to_i
    rescue ActiveRecord::RecordNotFound => e
      begin
      @user = User.where(email: ps[:selected_mail_mail].to_s).take
      rescue ActiveRecord::RecordNotFound => ex
        @user = nil
      end
    end
    if @user == nil
      if ps[:selected_mail_mail] =~ VALID_EMAIL_REGEX
        notice = 'Invited'
      else
        notice = 'Wrong email format'
      end
      respond_to do |format|
        format.js {flash[:notice] = notice}
        format.html {redirect_to dashboard_path, alert: 'Page not exists' }
      end
    else
      if @user.email == ps[:selected_mail_mail]
        if current_dashboard.users.include? @user
          notice = 'Already added'
        else
          notice = 'Added'
          current_dashboard.users << @user
        end
      else
        notice = 'Smth strange happen. Email for user changed?'
      end
      respond_to do |format|
        format.js {flash[:notice] = notice}
        format.html {redirect_to dashboard_path, alert: 'Page not exists' }
      end
    end
  end

  # GET /user_mails
  def user_mails
    @users = User.all.order(:visible_name)
    respond_to do |format|
      format.json
      format.html {redirect_to dashboard_path, alert: 'Page not exists' }
    end
  end
  
  # POST /dashboard/users
  def index_for_dashboard
    @owner = current_building.user
    @users = current_dashboard.users.order(:visible_name)
    render layout: false
  end
  
  # POST dashboard/users/permissions
  def edit_for_dashboard
    @users = current_dashboard.users.order(:visible_name)
    @roles = DashboardRole.all.order(:rank)
    @roles.each do |role|
      role.name = t 'dashboard_roles.' + role.name
    end
    render layout: false
  end

  def update_for_dashboard
    p = upd_params
    p[:selected_users].each do |u_id|
      ua = current_dashboard.dashboard_assignments.where(assignable: User.find(u_id)).take
      dr = DashboardRole.where(id: p[:dashboard_role_id]).take
      #byebug
      if ua != nil && dr != nil
        ua.update_attributes(dashboard_role: dr)
        #respond_to do |format|
        #  format.js
        #end
      else
        
      end
    end
    #byebug
  end
  
  # POST dashboard/users/remove_user
  def remove_for_dashboard
    @users = current_dashboard.users.order(:visible_name)
  end
  

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to controller: :users, action: :show, id: @user.id, notice: 'User was successfully created.', locale: I18n.locale }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:visible_name, :email, :password)
    end
    
    def inv_params
      params.permit(:selected_mail_id, :selected_mail_mail)
    end
    
    def upd_params
      params.permit(:dashboard_role_id, :selected_users => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_online(user)
     user.last_seen > 5.minutes.ago 
  end
  
  def user_get_current_state(user)
    if is_online(user)
      return 1
    elsif user.last_seen > 10.minutes.ago 
      return 2
    else
      return 0
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visible_name %><br>
    <%= f.text_field :visible_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit_for_dashboard.html.erb
<div id="user-permission-dashboard" class="dashboard-users">
  <h1 class="main-header"><%= t('.main_header') %></h1>
  
  <div class="table-responsive-vertical shadow-z-1">
    <%= form_tag 'dashboard/users/update_for_dashboard', remote: true do %>
      <h2 class="second-header"><%= label_tag :selected_users, "Select one user or more: " %></h2>
      <%= select_tag :selected_users, options_for_select(@users.map{|u| [u.public_data_for_dashboard(current_dashboard), u.id]}), {multiple: true, class: 'select_users_for_role form-control'} %>
      <h2 class="second-header"><%= label_tag :dashboard_role_id, "Select role to assign to selected user(s): " %></h2>
      <%= select_tag :dashboard_role_id, options_from_collection_for_select(@roles, :id, :name, 1), {class: 'select_role_dashboard form-control'} %>
      <%= button_tag id: 'save_perms_btn', class: 'set_users_permission', disabled: true do end %>
    <% end %>
  </div>
</div>

app/views/users/index_for_dashboard.html.erb
<div id="show-dashboard-users" class="dashboard-users">
    <h1 class="main-header"><%= t('.main_header') %></h1>
  <h2 class="second-header"><%= t('.second_header')%><%= @owner.visible_name %></h2>
  
  <div class="table-responsive-vertical shadow-z-1 table-striped">
     <table id="table" class="table table-hover table-mc-light-blue">
       <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>E-Mail</th>
          <th>Age</th>
          <th>Role</th>
          <th>Last logged</th>
          <th>Active</th>
        </tr>
       </thead>
       <tbody>
        <% for user in @users %>
        <% ucs = user_get_current_state(user) %>
          <tr>
             <td data-title="ID"><%= user.id %></td>
             <td data-title="Name"><%= user.visible_name %></td>
             <td data-title="E-Mail"><%= user.email %></td>
             <td data-title="Age"><%= distance_of_time_in_words_to_now(user.age) %></td>
             <td data-title="Role"><%= t "site_roles." + user.dashboard_assignments.where(dashboard: current_dashboard).take.dashboard_role.name %></td>
             <td data-title="Last logged"><%= user.last_login %></td>
             <td data-title="Active">
               <div class=
                  <%= "user-online" if ucs == 1 %>
                  <%= "user-offline" if ucs == 0 %>
                  <%= "user-afk" if ucs == 2 %>>
               </div>
             </td>
          </tr>
        <% end %>
       </tbody>
    </table>
  </div>
</div>

app/views/users/invite_new.html.erb
<div id="invite-user" class="dashboard-users">
  <h1 class="main-header"><%= t('.main_header') %></h1>
  <h2 class="second-header"><%= t('.second_header') %></h2>
  <div class="ui-widget">
    <%= form_tag 'dashboard/users/invite_user', remote: true do%>
      <%= text_field_tag 'invitation-email', nil, class: 'form-control user_mail_to_add' %>
      <%= hidden_field_tag 'selected_mail_id', '-1' %>
      <%= hidden_field_tag 'selected_mail_mail', 'NaN' %>
      <small class="text-muted">We'll never share your email with anyone else.</small>
      <br>
      <%= button_tag t('.invite'), id: 'invite_user_btn', data: { disable_with: "Please wait...", dismiss: "modal"}, class: 'invite_user_btn', disabled: true %>
    <% end %>
  </div>
  <div class="modal" id="user-add-modal" style="display:none;">
   <p id="user-add-body"></p>
  </div>
</div>

app/views/users/new.html.erb
<h1>Creating User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/remove_for_dashboard.html.erb
<div id="remove-dashboard-users" class="dashboard-users">
  <h1 class="main-header"><%= t('.main_header') %></h1>
  <h2 class="second-header"><%= t('.second_header')%></h2>
  
  <section id="list-users">
    <div class="container-fluid">
      <div class="row">
        <% count = 0 %>
        <% for user in @users %>
          <div class="col-md-4">
            <div class="button">
              <div class="background-user user-<%= user.id %> user-group-<%= user.dashboard_assignments.where(dashboard: current_dashboard).take.dashboard_role.name %>">
                <div class="row">
                  <div class="col-md-4">
                    <div class="avatar">
                      <%= image_tag('avatars/default.png', class:'avatar-img') %>
                    </div>
                  </div>
                  <div class="col-md-8">
                    <div class="info-about-user">
                      <p><%= user.visible_name %></p>
                      <p class="role"><%= user.dashboard_assignments.where(dashboard: current_dashboard).take.dashboard_role.name %></p>
                    </div>
                  </div>
                </div>
              </div>
              <button class="remove-user-approve-btn bottom-button" href="#" role="button">
                <span>remove</span>
                <div class="icon">
                  <i class="fa fa-remove"></i>
                  <i class="fa fa-check"></i>
                </div>
              </button>
            </div>
          </div>
          <% count = count + 1 %>
          <% if(count % 3 == 0) %>
            </div><div class="row top-space">
            <% count = 0 %>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Visible name:</strong>
  <%= @user.visible_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Was activated:</strong>
  <%= @user.was_activated %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user.id, locale: I18n.locale) %> |
<%= link_to 'Back', users_path %>