config/routes.rb
Rails.application.routes.draw do
  
  scope ':locale', :locale => /#{I18n.available_locales.join("|")}/ do
    get 'login'                          => 'sessions#new'
    post 'login'                         => 'sessions#create'
    delete 'logout'                      => 'sessions#destroy'
    get 'home'                           => 'home_pages#index', as: :home
    get 'about'                          => 'static_pages#about', as: :about
    get 'galery'                         => 'static_pages#galery', as: :galery
    get 'contact'                        => 'static_pages#contact', as: :contact
    get 'user/:id'                       => 'users#show', as: :account
    
    namespace :building do
      resources :laboratory do
        get 'reassign'                    => 'workstation#reassign'
        post 'move'                       => 'workstation#move'
        resources :workstation
      end
      post 'lab/new'                      => 'laboratories#new', as: :new_lab
      post 'lab/create'                   => 'laboratories#create'
      post 'labs'                         => 'laboratories#index'
    end
    resources :building, only: [:create, :new]
  
    get 'dashboard'                       => 'dashboard#index', as: :dashboard
    get 'dashboard/install'               => 'building#new', as: :building_install
    resources :dashboard, only: [:index]

   # TO DO: Change GET to POST
    get 'users/user_mails.json'          => 'users#user_mails'

    scope :dashboard do
      post 'users'                       => 'users#index_for_dashboard'
      scope :users do
        post 'invite_user_form'          => 'users#invite_new'
        post 'invite_user'               => 'users#invite_create'
        post 'permissions'               => 'users#edit_for_dashboard'
        post 'update_for_dashboard'      => 'users#update_for_dashboard'
        post 'remove_user'               => 'users#remove_for_dashboard'
      end
      post 'groups'                      => 'groups#index_for_dashboard', as: :groups
      scope :groups do
        post 'manage'                    => 'groups#manage'
        post 'add_group'                 => 'groups#new'
        post 'remove_group'              => 'groups#remove_group'
        post 'create'                    => 'groups#create'
      end

      post 'logs'                        => 'log#show', as: :logs
      post 'faq'                         => 'static_pages#faq', as: :faq
      post 'issues'                      => 'dashboard#issues', as: :issues
      
      post 'widgets'                     => 'dashboard#widgets_panel', as: :widgets
    end
    root to: redirect(status: 302) {|_,params, _| "/#{params[:locale]}/home"}
  end
  
  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
end

app/models/active_widget.rb
class ActiveWidget < ActiveRecord::Base
  belongs_to :dashboard_user_setting
  belongs_to :widget
  
  validates :widget, presence: true
  validates :dashboard_user_setting, presence: true
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  
  validates :url, presence: true
end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :user
  belongs_to :dashboard
  belongs_to :company_type
  belongs_to :country
  has_many :laboratories

  before_validation :default_values
  
  accepts_nested_attributes_for :country
  
  validates :name, presence: true, uniqueness: true
  validates :shortname, presence: true, uniqueness: true
  validates :company_type, presence: true
  validates :country, presence: true

  def default_values
    self.dashboard ||= Dashboard.create
    DashboardAssignment.create(dashboard: dashboard, assignable_id: self.user.id, assignable_type: 'User')
  end
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :building
  
  validates :name, presence: true, uniqueness: true
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :buildings
  
  validates :name, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_one :building
  has_many :dashboard_assignments
  has_many :users, through: :dashboard_assignments, source: :assignable, source_type: "User"
  has_many :groups, through: :dashboard_assignments, source: :assignable, source_type: "Group"
  
  def assignments_for_user(user)
    dashboard_assignments.where(users: {id: user.id})
  end
end

app/models/dashboard_role.rb
class DashboardRole < ActiveRecord::Base
  has_many :dashboard_assignments
  
  validates :name, presence: true, uniqueness: true
  validates :rank, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_one :dashboard_assignment, as: :assignable
  has_one :dashboard, through: :dashboard_assignment
  has_many :laboratories_assignments, as: :lab_assignable
  has_many :users_groups
  has_many :users, through: :users_groups

  validates :name, presence: true, uniqueness: false
  validates :dashboard_assignment, presence: true, uniqueness: false
end

app/models/lab_role.rb
class LabRole < ActiveRecord::Base
  has_many :laboratory_assignments
  
  validates :name, presence: true, uniqueness: true
  validates :rank, presence: true, uniqueness: true
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
  belongs_to :building
  has_many :workstations
  
  validates :name, presence: true
  validates :building, presence: true
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :log_type

  validates :log, presence: true
  validates :category, presence: true
end

app/models/log_type.rb
class LogType < ActiveRecord::Base
  has_many :log
  
  validates :name, presence: true, uniqueness: true
  validates :rank, presence: true, uniqueness: true
end

app/models/site_role.rb
class SiteRole < ActiveRecord::Base
  has_many :users
  
  validates :name, presence: true, uniqueness: true
  validates :rank, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  belongs_to :site_role
  has_many :buildings
  has_many :dashboard_assignments, as: :assignable, class_name: 'DashboardAssignment'
  has_many :laboratories_assignments, as: :lab_assignable
  has_many :dashboards, through: :dashboard_assignments
  
  def is_new_user
    is_normal_user || self.site_role == SiteRole.find_by_name('new_user')
  end
  
  def is_normal_user # can create own dashboard
    is_mod || self.site_role == SiteRole.find_by_name('user')
  end
  
  def is_mod
    is_hmod || self.site_role == SiteRole.find_by_name('moderator')
  end
  
  def is_hmod
    is_admin || self.site_role == SiteRole.find_by_name('head_moderator')
  end
  
  def is_admin
    is_hadmin || self.site_role == SiteRole.find_by_name('administrator')
  end
  
  def is_hadmin
    self.site_role == SiteRole.find_by_name('head_administrator')
  end
  
  def current_avatar
    return "default.png"
  end
  
  def public_data_for_dashboard(dashboard)
    da=dashboard.dashboard_assignments
    visible_name + ' <' + email + '> - ' + I18n.t("dashboard_roles." + dashboard.dashboard_assignments.where(assignable: self).take.dashboard_role.name)
  end
  
  def assigments_for_dashboard(dashboard)
    as = current_dashboard_assignments
    as.where(user: self).take
  end
  
  validates :visible_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :site_role, presence: true
  validates :age, presence: true
  
end

app/models/users_avatar.rb
class UsersAvatar < ActiveRecord::Base
  belongs_to :avatar
  belongs_to :user

  validates :avatar, presence: true
  validates :user, presence: true
end

app/models/users_group.rb
class UsersGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user, presence: true, uniqueness: {scope: :group}
  validates :group, presence: true, uniqueness: false
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  has_many :dashboard_user_settings, through: :active_widgets
  
  validates :name, presence: true, uniqueness: true
end

app/models/workstation.rb
class Workstation < ActiveRecord::Base
  belongs_to :laboratory

  validates :name, presence: true
  validates :number, presence: true, uniqueness: {scope: :laboratory_id}
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_online(user)
     user.last_seen > 5.minutes.ago 
  end
  
  def user_get_current_state(user)
    if is_online(user)
      return 1
    elsif user.last_seen > 10.minutes.ago 
      return 2
    else
      return 0
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "<%= current_locale %>">
<head>
  <title><%= t('.title_page') %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Dawid 'Rodzyn' Tomas, Lukas Levvy">
  <meta name="description" content="<%= t('layouts.static_header.header_unsigned_text') %>">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if GoogleAnalytics.valid_tracker? %>
</head>
<% if is_login_panel %>
  <body class="login_page">
    <%= render :template => 'sessions/new' %>
  </body>
<% else %>
  <body class=  "<%= current_user ? 'body_signed' : 'body_unsigned' %><%= is_dashboard ? ' body-dashboard' : ''  %>">
    <header id="header" class="<%= params[:controller] == 'dashboard' ? 'header-dashboard' : 'navbar-fixed-top'  %>">
     <%= yield :header %>
    </header>
    <section id="content">
      <%=content_for?(:content) ? yield(:content) : yield %>
    </section>
    <footer id="footer">
      <%= yield :footer %>
    </footer>
    <div id="modals">
      <% if flash[:alert] || content_for?(:alertbody) %>
        <div class="modal fade" id="modalinfo" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-lg">
             <div class="modal-content">
               <div class="modal-header">
                <h4 class="modal-title">
                <%= if content_for?(:alerttitle)
                      yield :alerttitle
                    else
                      t 'errors.no_access_title'
                    end %></h4>
               </div>
               <div class="modal-body">
                 <p><%= yield :alertbody %></p>
                 <p><%= flash[:alert] %></p>
               </div>

             </div>
          </div>
        </div>
        <% end %>
        <% if content_for?(:noticebody) %>
          <div class="modal fade" id="modalinfo" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg">
             <div class="modal-content">
               <div class="modal-header">
                <h4 class="modal-title"><%= yield :noticetitle %></h4>
               </div>
               <div class="modal-body">
                 <p><%= yield :noticebody %></p>
               </div>
               <div class="modal-footer">
                 <button type="button" class="btn btn-white" ng-click="cancel()"><%= t '.close' %></button>
                 <button type="button" class="btn btn-primary" ng-click="ok()"><%= t '.ok' %></button>
               </div>
             </div>
          </div>
        </div>
      <% end %>
    </div>
  </body>
<% end %>
</html>

app/views/layouts/dashboard_header.html.erb
<div class="container-fluid navbar-fixed-top">
  <div class="row">
    <div class="col-md-2 db-background-buliding">
      <div class="dashboard_top">
        <p class="dash-title-top"><%= t('activerecord.attributes.company_type.' + CompanyType.find(current_building.company_type_id).name.downcase) + ': ' + current_building.shortname %></p>
      </div>
    </div>
    <div class="col-md-10 db-background-person">
        <div class="avatar">
          <%= image_tag('avatars/default.png', class:'avatar-img img-circle') %>
        </div>
        <p class="user-show-name pull-left"><%= @current_user.visible_name %> 
          <span class="permission"> 
            (<%= if @current_user.is_admin 
                  t 'perms.admin'
                  else
                  t 'perms.user'
                  end %>)
           </span>
        </p>
        <% if current_user %>
          <p class="user-show-logout pull-right"><%= link_to t('.logout'), logout_path, method: 'delete' %></p>
        <% end %>
        <div class="language pull-right">
          <p class="user-show-lang pull-left"><%= t('activerecord.attributes.dashboard.language')%></p>
          <li class="current-lang dropdown pull-right">
            <%= button_tag "#", {class: "btn btn-dropdown dropdown-toggle select_lang flag", id: 'lang_'+I18n.locale.to_s, data: {toggle: "dropdown"}} do end %>
            <ul class="dropdown-menu select_lang_list">
              <% @locales.each do |l| %>
                <% if I18n.locale.to_s != l.to_s %>
                  <li>
                    <%= link_to dashboard_path(locale: l.to_s), {class: 'flag lang', id: 'lang_'+l.to_s} do end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        </div>
        <p class="user-show-last-login pull-right"><%= t('activerecord.attributes.dashboard.last_login')%> <span class="date"><%= session[:last_login].to_time.strftime('%d.%m.%Y / %H:%M') %></span> <%= t('activerecord.attributes.dashboard.last_ip')%> <span class="ip"><%= session[:last_ip] %></span></p>
    </div>
  </div>
</div>

app/views/layouts/signed_header.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      
    </div>
    <div class="col-md-8">
      
    </div>
  </div>
</div>

app/views/layouts/static_footer.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <p class="center-height center-text">Copyright &copy; <%= Time.now.year %> - <%= t('.copyright') %></p>
        </div>
        <div class="col-md-4">
            <p class="center-text"><%= t('.version') %> Pre-Alpha 0.0.7 <br><i>Dev Demo Preview</i></p>
        </div>
        <div class="col-md-4">
            <p class="center-text">
                <%= t('.authors') %> <%= link_to 'Rodzyn', 'http://rodzyn.pl', target: "_blank" %>, 
                <%= link_to 'Lucas Levvy', 'https://player.me/levvy', target: "_blank" %>
                <br>
                <%= t('.designer') %> <%= mail_to "tomekbrylinski.39@gmail.com", 'Tomasz Bryliński' %>
            </p>
        </div>
    </div>
</div>

app/views/layouts/static_header.html.erb
  <div class="container">
      <div class="row">
          <div class="col-md-5">
              <p><%= t ('.header_unsigned_text') %></p>
          </div>
          <div class="col-md-7">
              <nav class="navbar pull-right" role="navigation">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#inventory">
                      <span class="sr-only"><%= t '.expand' %></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                  </div>
                  <div class="collapse navbar-collapse" id="inventory">
                    <ul class="nav navbar-nav">
                      <li <%= 'class=active' if current_page?(controller: 'home_pages') %>><%= link_to t('.home'), root_path %> </li>
                      <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'about') %>><%= link_to t('.about'), about_path %> </li>
                      <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'galery') %>><%= link_to t('.galery'), galery_path %> </li>
                      <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'contact') %>><%= link_to t('.contact'), contact_path %> </li>
                      <li class="login">
                        <% if !current_user %>
                        <%= link_to t('.login'), login_path %>
                        <% else %>
                        <%= link_to t('.panel'), dashboard_index_path %>
                        <% end %>
                      </li>
                      <% if current_user %>
                      <li><%= link_to t('.logout'), logout_path, method: 'delete' %></li>
                      <% end %>
                      <li class="dropdown">
                        <%= button_tag "#", class: "btn btn-dropdown dropdown-toggle select_lang", data: {toggle: "dropdown"} do %>
                          <%= I18n.locale %>
                        <% end %>
                        <ul class="dropdown-menu select_lang_list">
                          <% @locales.each do |l| %>
                            <li>
                              <% if I18n.locale.to_s == l.to_s %>
                                  <%= link_to '#', {class: 'btn btn-primary lang active'} do l.to_s end %>
                                <% else %>
                                  <%= link_to params.merge({:locale => l.to_s}), {class: 'btn btn-primary lang'} do l.to_s end %>
                                <% end %>
                            </li>
                          <% end %>
                        </ul>
                      </li>
                    </ul>
                  </div>
              </nav>
          </div>
      </div>
  </div>

app/views/layouts/unsigned_header.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <p><%= t('header_unsigned_text') %></p>
        </div>
        <div class="col-md-7">
            <nav class="navbar pull-right" role="navigation">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#inventory">
                    <span class="sr-only">Rozwiń nawigację</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div class="collapse navbar-collapse" id="inventory">
                  <ul class="nav navbar-nav">
                    <li <%= 'class=active' if current_page?(controller: 'home_pages') %>><%= link_to t('menu.home'), root_path %> </li>
                    <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'about') %>><%= link_to t('menu.about'), about_path %> </li>
                    <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'galery') %>><%= link_to t('menu.galery'), galery_path %> </li>
                    <li <%= 'class=active' if current_page?(controller: 'static_pages', action: 'contact') %>><%= link_to t('menu.contact'), contact_path %> </li>
                    <li class="login">
                      <% if !current_user %>
                      <%= link_to t('session.login'),"#", {'data-toggle': "modal", 'data-target': "#login_modal"} %>
                      <% else %>
                      <%= link_to t('menu.panel'), "#" %>
                      <% end %>
                    </li>
                    <% if current_user %>
                    <li><%= link_to t('session.logout'), logout_path, method: 'delete' %></li>
                    <% end %>
                    <li class="dropdown"><%= button_tag "#", {class: "btn btn-dropdown dropdown-toggle select_lang", 'data-toggle': "dropdown"} do %>
                      <%= I18n.locale %> <i class="fa fa-caret-down"></i>
                      <% end %>
                      <ul class="dropdown-menu select_lang_list">
                        <% @locales.each do |l| %>
                          <li>
                            <% if I18n.locale.to_s == l.to_s %>
                                <%= link_to '#', {class: 'btn btn-primary lang active'} do l.to_s end %>
                              <% else %>
                                <%= link_to params.merge({:locale => l.to_s}), {class: 'btn btn-primary lang'} do l.to_s end %>
                              <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>
                </div>
            </nav>
        </div>
    </div>
</div>